facebook: "https://facebook.com/example"
twitter: "https://twitter.com/example"
email: "lyt.0628@qq.com"
name: "摸鱼天尊"
location: New York
phone: (999) 999-9999
hours: "**Mon-Fri:** 9:00AM - 6:00PM, ET"