# 页面发布成功, 但404,说明baseurl错误
# baseURL: https://lyt0628.github.io/
baseURL: https://lyt0628.icu/
languageCode: zh-CN
title: 摸鱼天尊
# theme: CyberLoafing
theme: github.com/LYT0628/CyberLoafing
enableEmoji: true
enableGitInfo: true
paginate: 8


module:
  hugoVersion:
    min: 0.19.2
  imports:
    - path: github.com/LYT0628/hugoftp